// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izgwtzihonzlbywogjru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6Z3d0emlob256bGJ5d29nanJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzAyOTQsImV4cCI6MjA2NTU0NjI5NH0.qa5k2-nGbEFOxKSZFlMD-ZFStX_cQkPiPXG6MSe2Z1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);